name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feat'
      - 'feature'
      - '!feat'
      - '!feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    label: 'chore'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
      - '!feature'
      - '!feat'
  minor:
    labels:
      - 'minor'
      - 'feat'
      - 'feature'
  patch:
    labels:
      - 'patch'
      - 'fix'
      - 'chore'
      - 'bugfix'
      - 'bug'
  default: patch
template: |
  ## Changes

  $CHANGES
