name: Check Manifest Version Bump

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write  # Required to comment on PRs

jobs:
  check_version_bump:
    name: Ensure version is updated in manifest.json
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get base branch
        run: echo "BASE_REF=${{ github.event.pull_request.base.ref }}" >> $GITHUB_ENV

      - name: Checkout base manifest.json
        run: |
          git fetch origin $BASE_REF
          git show origin/$BASE_REF:custom_components/ocado/manifest.json > ../manifest_base.json
          
      - name: Compare manifest versions
        id: compare
        run: |
          BASE_VERSION=$(jq -r '.version' ../manifest_base.json)
          CURRENT_VERSION=$(jq -r '.version' custom_components/ocado/manifest.json)

          echo "Base version: $BASE_VERSION"
          echo "Current version: $CURRENT_VERSION"

          if [ "$BASE_VERSION" == "$CURRENT_VERSION" ]; then
            echo "unchanged=true" >> $GITHUB_OUTPUT
            exit 1
          else
            echo "unchanged=false" >> $GITHUB_OUTPUT
          fi

      - name: Comment on PR if version unchanged
        if: steps.compare.outputs.unchanged == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --body "⚠️ **manifest.json version has not been updated.**
          
          Please update the \`version\` field in \`manifest.json\` according to [Semantic Versioning](https://semver.org/), based on the type of change (!feature (breaking change), feature, patch)."
