name: My Workflow
on: [pull_request]
jobs:
  update_manifest:
    runs-on: ubuntu-latest
    # needs: 
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: '"version": "v\d+\.\d+.\d+"'
          replace: '"version": "v{{}}"'
          include: "manifest.json"
          regex: True
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
